# Triggers Pipeline only on Master
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - LICENSE

# Disables triggering Pipeline run at creation of every Pull Request
pr: none


variables:
  agent-pool: 'build-dev-agent'

stages:
# Continuous Integration steps
- stage: CI
  displayName: 'Continuous Integration'
  pool: '$(agent-pool)'
  # Validation jobs
  jobs:
  - job: Validate
    
   
    steps:
    # Upload Kubernetes manifests to current artifact Pipeline from folder /k8s
    - script: terraform -version
    - script: docker --version
    - script:  which astro